### ISSUE TITLE
2020~2021 学年的时间表

### ISSUE THREAD

**Issue by Hagb** [zombie110year/cli_cqu#6]
[重庆大学2020-2021学年校历.pdf](https://github.com/zombie110year/cli_cqu/files/4772147/1.2020-2021.pdf)
附件是从老师那获得的，不清楚原出处。
如附件所示：下学年的时间表和以往相比发生了改变，并且不再区分老校区和新校区了（新老校区时间一致了）。

**Comment by Hagb** [comment]
教务网正式公告：[关于印发《重庆大学2020-2021学年校历》的通知](http://jwc.cqu.edu.cn/node/4671)

**Comment by zombie110year** [comment]
新的作息时间已经实装。另外，交互方式也发生了改变，注意看 README。
